DoctrineExamples\ManyToManyBidirectional\Entity\User:
    type: entity
    table: manyToMany_user

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                unsigned: true

    manyToMany:
        credentials:
            targetEntity: DoctrineExamples\ManyToManyBidirectional\Entity\Credential
            inversedBy: users
            cascade: [persist]
            joinTable:
                name: manyToMany_user_credential
