DoctrineExamples\Entity\User:
    type: entity
    table: user

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                unsigned: true

    manyToMany:
        credentials:
            targetEntity: DoctrineExamples\Entity\Credential
            inversedBy: users
            cascade: [persist]
            joinTable:
                name: users_credentials

    oneToMany:
        comments:
            targetEntity: DoctrineExamples\Entity\Comment
            mappedBy: user
