DoctrineExamples\Entity\Credential:
    type: entity
    table: credential

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                unsigned: true

    manyToMany:
        users:
            targetEntity: DoctrineExamples\Entity\User
            # Credential is defined as inverse side by defining User::$credentials as owning side
            mappedBy: credentials
            cascade: [persist]
