services:
    php:
        image: php:8.2.8-fpm-alpine3.18
        container_name: doctrine-examples_php
        build:
            context: ..
            dockerfile: docker/php/Dockerfile
        user: ${DOCKER_UID}:${DOCKER_GID}
        depends_on:
            - mysql
        volumes:
            - ..:/app
        working_dir: /app

    mysql:
        image: mysql:8.0.33-debian
        container_name: doctrine-examples_mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=doctrine_examples
